version: "3.5"

services:
  zerotier-moon:
    image: ghcr.io/gythialy/zerotier-one-moon:latest
    container_name: zerotier-moon
    cap_add:
      - NET_ADMIN
      - SYS_ADMIN
    devices:
      - /dev/net/tun
    ports:
      - 9993:9993/udp
    command:
      - -4 xxx.xxx.xxx.xxx
      - -p 9993
    volumes:
      - ./zerotier-one:/var/lib/zerotier-one
